server:
  port: ${SERVICE_PORT:8083}
  servlet:
    context-path: /api

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ru.itk.app.model
        spring.json.value.default.type: ru.itk.app.model.PaymentEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  shipping:
    consumer:
      topic: payed_orders
      group-id: shipping-group
      concurrency: 3

logging:
  level:
    ru.itk.app: ${LOG_LEVEL:DEBUG}
    org.apache.coyote.http11.Http11Processor: ERROR